# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e4504d1db8ee1dd98fc2fc40a6b3364d26f655fb50f11709111868d8fca2d6c3fffe910a707616fb082ee9cd7902f25b7d54d84a930fe150de7adabf6f27eae

test:
  secret_key_base: 5d9e099f4d913de6ad7edc92e34165f3e41cd2fef542f19cfabb87e30d388c4b6aae351a6d6db72f65bcb3999fac02978af7a315c320990d3f2e6a0da0f2934b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
